name: Static Check

on: [pull_request, push]

jobs:
  prospector-diff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      # Checks out repository for other checks to run
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Prospector
        run: pip install prospector
      - name: check-branch
        run: |
          prospector -s veryhigh -o json:branch-results.json -o text:branch-results.txt -0 --max-line-length 200
          cat branch-results.txt

      - name: checkout-target
        if: ${{ github.event_name == 'pull_request' }}
        run: git checkout origin/$GITHUB_BASE_REF
      - name: checkout-previous
        if: ${{ github.event_name == 'Push' }}
        run: git checkout HEAD~1

      - name: check-reference
        run: |
          prospector -s veryhigh -o json:reference-results.json -o text:reference-results.txt -0 --max-line-length 200
          cat reference-results.txt

      - name: compare-results
        run: |
          new_count=`jq .summary.message_count branch-results.json`
          old_count=`jq .summary.message_count reference-results.json`
          echo New warning Count: $new_count
          echo Old warning Count: $old_count
          (( $new_count <= $old_count ))
